[package]
name = "wasm"
version = "0.1.0"
edition = "2021"

[lints]
workspace = true

[lib]
crate-type = ["cdylib"]

[dependencies]
instant = { version = "0.1.13", features = ["wasm-bindgen"] }
js-sys = "0.3.76"
oxc = { workspace = true }
rewriter = { version = "0.1.0", path = "../rewriter", default-features = false }
thiserror = "2.0.6"
wasm-bindgen = "0.2.99"
web-sys = { version = "0.3.76", features = ["Url"] }

[features]
default = ["debug"]
debug = ["rewriter/debug"]
